name = "Nitkit"
author = "Nitkit"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f3abfdf5f0d39d29f38846eebfcdb7621bbb704ea6823603f050c0f8fe3cf6e"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
