name = "Nitkit"
author = "Nitkit"
version = "0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15161d63d2f667185cdb85207909fbf87111dcb1732d5870ac147c98bb555c85"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
